puma560:
  # Publicar todos los joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Effort Controllers
  joint_waist_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_base_to_waist
    pid: {p: 1000.00, i: 0.0, d: 10.0}  
  joint_shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_waist_to_shoulder
    pid: {p: 1000.00, i: 0.0, d: 10.0}  
  joint_elbow_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_shoulder_to_elbow
    pid: {p: 1000.00, i: 0.0, d: 10.0}  
  joint_wrist_bend_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_elbow_to_wrist_bend
    pid: {p: 1000.00, i: 0.0, d: 10.0}  
  joint_wrist_roll_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wrist_bend_to_roll
    pid: {p: 1000.00, i: 0.0, d: 10.0}  