# Configuracion de controladores de posicion

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50   # 50 Hz

joint_pos_controller_waist:
  type: position_controller/JointPositionController
  joint: joint_base_to_waist  
#  pid: {p: 100.00, i: 0.0, d: 10.0 }  
joint_pos_controller_shoulder:
  type: position_controller/JointPositionController
  joint: joint_waist_to_shoulder
#  pid: {p: 100.00, i: 0.0, d: 10.0 }  
joint_pos_controller_elbow:
  type: position_controller/JointPositionController
  joint: joint_shoulder_to_elbow  
#  pid: {p: 100.00, i: 0.0, d: 10.0 }  
joint_pos_controller_wrist_bend:
  type: position_controller/JointPositionController
  joint: joint_elbow_to_wrist_bend  
#  pid: {p: 100.00, i: 0.0, d: 10.0 }  
joint_pos_controller_wrist_roll:
  type: position_controller/JointPositionController
  joint: joint_wrist_bend_to_roll
#  pid: {p: 100.00, i: 0.0, d: 10.0 }  

/gazebo_ros_control:
  pid_gains:
    joint_base_to_waist: 
      p: 100.0
      i: 0.01
      d: 10.0
    joint_waist_to_shoulder: 
      p: 100.0
      i: 0.01
      d: 10.0
    joint_shoulder_to_elbow: 
      p: 100.0
      i: 0.01
      d: 10.0
    joint_elbow_to_wrist_bend: 
      p: 100.0
      i: 0.01
      d: 10.0
    joint_wrist_bend_to_roll: 
      p: 100.0
      i: 0.01
      d: 10.0
